### ISSUE TITLE
How to use "out" animation?

### ISSUE THREAD

**Issue by lzmhhh123** [BlackBoxVision/styled-animation#4]
I have a question. The `<Animation>` is great useful for `name="xxxInxx"`. But when "out" animation complete, the content in `<Animation>`  still exist. I have no idea how to solve this   problem.

**Comment by danigomez** [comment]
Hi, thanks for using styled-animation!
I will take a look at this later today, i will add a prop to specify if you want or not to reset the animation when it finished, 
i think that that will solve the problem.

**Comment by danigomez** [comment]
Already fixed!, Take a look at version 1.0.4

**Comment by danigomez** [comment]
With this change finished animation will not replay unless you specify it with the `fillMode` prop

**Comment by lzmhhh123** [comment]
Hello,
I have looked through the new version code. Then I learned css element `animation-fill-mode`.I changed the styled-animation version to 1.0.4 in package.json and re `yarn install`. But the code `<Animation name="fadeOut" duration="2s">
          <img className="gif" src="/image/preview_1.gif" />
        </Animation>` still didn't work. I mean the `<img className="gif" src="/image/preview_1.gif" />` still exist when animation finish.

**Comment by danigomez** [comment]
I think that i can add two callbacks in the `Animation` component,
`onStart` and `onEnd`, where you can handle a state in your component to unmount or not the `Animation` component, that will be useful to you??

**Comment by lzmhhh123** [comment]
OK, after you add them. I will have a try.

**Comment by danigomez** [comment]
I added the `onEnd`  callback, give it a try

**Comment by lzmhhh123** [comment]
Thanks a lot!
Effective now.

**Comment by lzmhhh123** [comment]
Sorry to bother you, but I think the `onStart` is useful too.
Could you add this feature If you are free?

**Comment by danigomez** [comment]
I'm going to close this issue and open a new one to add that callback
